[package]
name = "tsuga"
version = "0.1.0"
authors = ["chrism <christopher.and.moran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tsuga"
# crate-type = ["rlib","staticlib","cdylib"]

[dependencies]
ndarray = { version = "0.13.0", features = ["rayon","blas"] }
blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.0", default-features = false, features = ["cblas", "system"] }

ndarray-stats = "0.3"
ndarray-rand = "0.11.0"
image = "0.23.3"
imageproc = "0.20"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7.3"

ocl = "0.19"
ocl-extras = "0.1.1"
serial_test = "0.4"

#carya = {path = "./carya"}
carya = {git = "https://github.com/quietlychris/carya.git", branch="master"}
