[package]
name = "tsuga"
version = "0.1.0"
authors = ["chrism <christopher.and.moran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tsuga"
# crate-type = ["rlib","staticlib","cdylib"]

[dependencies]
ndarray = { version = "0.13.0", features = ["rayon"] }

ndarray-stats = "0.3"
ndarray-rand = "0.11"
image = "0.23"
imageproc = "0.20"
rand = "0.7"

serial_test = "0.4"

[dependencies.carya]
git = "https://github.com/quietlychris/carya.git"
# path = "./carya"
optional = true

[dependencies.ocl]
version = "0.19"
optional = true

[profile.release]
debug = true

[features]
default = []
gpu = ["carya","ocl"]

[dev-dependencies]
mnist = "0.4"
minifb = "0.17"
